### ISSUE TITLE
Getting a data key that doesn't yet exist throws native errors

### ISSUE THREAD

**Issue by swamijones** [emeraldsanto/react-native-encrypted-storage#11]
When calling EncryptedStorage.getItem() on a key that has not yet been stored:
iOS throws: Error: Unknown error from a native module
Android throws: Error: An error occured while retrieving [key_name]

The example documentation has a check for !== null on the return, which led me to expect a null return in this case. Took us a while to realize where the error was actually being thrown.

Could be just a documentation update to make this more clear.

**Comment by emeraldsanto** [comment]
Thanks for reporting this! Which version of the package are you using? I just pushed an update last night (version 2.1.0) with a few fixes.

**Comment by swamijones** [comment]
We saw this in 2.0.1. I'll update to 2.1.0 and check it.

**Comment by swamijones** [comment]
Looks resolved in 2.1.0 on our end, returns an undefined which I assume is what you intended here. Thanks for the quick response!
