### ISSUE TITLE
Retrieving data shows undefined.

### ISSUE THREAD

**Issue by ad77076** [emeraldsanto/react-native-encrypted-storage#121]
When I'm trying to read data from EncryptedStorage, the data is shown in object format( which is perfect and expected), but when I try to extract an individual data/key from the object , it shows undefined !
![photo_6339029587962476991_y](https://github.com/emeraldsanto/react-native-encrypted-storage/assets/60743775/3fa7a52c-cdad-417e-9638-e47cf96b83ac)

**Comment by davidteejay** [comment]
Data should normally be stored in the storage as a string. If `session` is a stringified object, you have to parse the string first before accessing the `num` key, so it should be `JSON.parse(session).num`
