### ISSUE TITLE
Feature request: Expose security framework result code when throwing error

### ISSUE THREAD

**Issue by svenlombaert** [emeraldsanto/react-native-encrypted-storage#20]
Hi there,

We saw a huge spike in Sentry about an error that this package throws on iOS. It's weird since we haven't upgrade this package. We did upgrade react native to 0.62.2 though.

**Error** `getItem(react-native/Libraries/BatchedBridge/NativeModules)`
**An error occured while retrieving value**

I know this can happen, and it's our mistake of not handling the error properly.

But, it would be very handy if the [result code](https://developer.apple.com/documentation/security/1542001-security_framework_result_codes) was shown in that error as well. That way we have a starting point for debugging purposes, since it's not on a specific device, nor a specific iOS version, and it only started happening on our latest release.

**Comment by emeraldsanto** [comment]
Hi! I'm sorry to hear that, I can definitely look into forwarding this kind of info though. I'm wondering if the base AsyncStorage module does this or not. Regardless, it should be an easy fix and I'll try to release a new version in the upcoming days.

**Comment by svenlombaert** [comment]
We've been using this in production without any problems in our past releases, so it's probably on our end. But this would help us a lot in the debugging process!

**Comment by emeraldsanto** [comment]
I've got the code up and running locally, I've tested by rejecting with arbitrary `OSStatus` members such as `errSecNoSuchKeychain` and the equivalent code (`-25294`) was sent back to JS in the `error.code` property. I then used [osstatus.com](https://www.osstatus.com/search/results?platform=all&framework=all&search=-25294) to search for the code and check if the results matched the native error.

This experiment was successful and you can expect a release tomorrow morning, or rather afternoon in Belgium 😅

**Comment by svenlombaert** [comment]
Thanks for the quick reply and work man - much appreciated!

**Comment by emeraldsanto** [comment]
My pleasure, I went ahead and released the new version (`2.4.4`) which includes this. You may have to wait a moment before npm propagates it before updating. Don't hesitate to tell me if anything else comes up!

**Comment by emeraldsanto** [comment]
Also wanted to point out that the most frequent case for errors being thrown is trying to remove items which don't exist, in case that could be useful to you!
