### ISSUE TITLE
Minimum SDK version - it wants 23 not 16

### ISSUE THREAD

**Issue by garyhuntddn** [emeraldsanto/react-native-encrypted-storage#22]
I was trying to get my own project working and hitting issues - so thought I'd try the example in the git repo.

The only way I could get it to work was by changing the minSdkVersion from 16 to 23.

I see that #13 appears to be the same issue but is marked as closed.

Could it be that there's a regression between 2.30 and 2.4.4?

Obviously changing this setting in my project has fixed it but wondered whether it was just my environment or whether updating the example is now required.

cheers,

g

-------

```
diff --git a/example/android/build.gradle b/example/android/build.gradle
index 5d5d188..047ea3c 100644
--- a/example/android/build.gradle
+++ b/example/android/build.gradle
@@ -3,7 +3,7 @@
 buildscript {
     ext {
         buildToolsVersion = "28.0.3"
-        minSdkVersion = 16
+        minSdkVersion = 23
         compileSdkVersion = 28
         targetSdkVersion = 28
     }
```

**Comment by emeraldsanto** [comment]
Hi! Thanks for reporting, I just checked and indeed, you need to add a special anotation to the root tag of your `AndroidManifest.xml`:

```xml
<!--
    Overrides warning about AndroidX Security package only running on API 23+
    There is a runtime check to make sure that this API is not accessed below API 23
-->
<uses-sdk tools:overrideLibrary="androidx.security" />
```

There is a runtime check in this library making sure to use the normal `SharedPreferences` when on API 23 or lower. I will add this to the docs, unfortunately I could not find a better way to handle this.

**Comment by emeraldsanto** [comment]
Alrighty, turns out I can include the same tag inside the library's manifest so you won't have to. This will be coming in a patch release tonight or tomorrow!

**Comment by garyhuntddn** [comment]
Nice one Yanick, cheers, g

**Comment by AdrianBordeianu** [comment]
The issue is not fixed, the manifest does not have uses-sdk line, only after I add both this
<uses-sdk tools:overrideLibrary="androidx.security" />
 in react-native-encrypted-storage Manifest
<img width="579" alt="Screenshot 2020-09-10 at 08 59 57" src="https://user-images.githubusercontent.com/37770519/92687365-142c6180-f344-11ea-9ee7-c506f8fc95a6.png">

and 
multiDexEnabled true  (in app build.gradle defaultConfig)
implementation 'androidx.multidex:multidex:2.0.1' (in app build.gradle)

it works

**Comment by josiahking** [comment]
This issue is yet to be fixed, i have tried all the fixed except for changing the minSdk to 23.

**Comment by Snowirbix** [comment]
Hello you made a pull request to fix this
And then in your commit "Bumped to min sdk 23"
You remove the fix
Can you fix it again @emeraldsanto please ?

**Comment by emeraldsanto** [comment]
Prior to https://github.com/emeraldsanto/react-native-encrypted-storage/pull/35, it was not possible to support < API 23. The new minimum is API 21, anything below this will crash since the AndroidX Security dependency requires this.

**Comment by CoolMind** [comment]
> Hi! Thanks for reporting, I just checked and indeed, you need to add a special anotation to the root tag of your `AndroidManifest.xml`:
> 
> ```
> 
> <uses-sdk tools:overrideLibrary="androidx.security" />
> ```
> 
> There is a runtime check in this library making sure to use the normal `SharedPreferences` when on API 23 or lower. I will add this to the docs, unfortunately I could not find a better way to handle this.

Thanks! It helped in a usual Android application.
