### ISSUE TITLE
Getting RNEncryptedStorageError: An error occured while saving value.

### ISSUE THREAD

**Issue by TaraSinghDanu** [emeraldsanto/react-native-encrypted-storage#29]
<img width="914" alt="Screenshot 2020-10-03 at 2 35 40 PM" src="https://user-images.githubusercontent.com/16621822/94987691-c5aa6580-0585-11eb-849c-5172a872bd6a.png">

try {
        await EncryptedStorage.setItem(
          'showCeanOnboarding',
            'false'
        );
    } catch (error) {
        console.log('error setShowCeanOnboarding', error)
    }

    "react-native-encrypted-storage": "^3.0.0",

Platform :ios

Working fine in Android

**Comment by emeraldsanto** [comment]
Hi! Can you try logging `error.code` as specified in the [README](https://github.com/emeraldsanto/react-native-encrypted-storage#error-handling)?

**Comment by shridhar52war** [comment]
@emeraldsanto We are also getting the same error in production for iOS. Error Code being: `-25308`.

**Comment by emeraldsanto** [comment]
Here's a thread regarding this specific iOS error in case it may help you: https://developer.apple.com/forums/thread/114159

**Comment by shridhar52war** [comment]
@emeraldsanto Link did not help, we are getting errors in retrieving the values now. `RNEncryptedStorageError: An error occured while retrieving value`. All errors occurred in iOS

**Comment by shubhnik** [comment]
Yeah, we are also getting the same `-25308` errors while saving/retrieving values on ios. The link doesn't help much in understanding the cause. Anyone have any idea, like under which circumstances this error can occur?

**Comment by DineshKachhot** [comment]
We are also getting this error in iOS, android working fine, is there any solution yet, or any other options ?

**Comment by coucoseth** [comment]
getting the same error in ios, any fix yet?

**Comment by manikandanbaskara** [comment]
We're facing same error `-25308`. Couldn't find the root cause. Any help would be much appreciated

**Comment by renchap** [comment]
Errors -25308 are caused by accessing the keychain while the app is not active / the phone is locked.

See #68 for an explanation and a workaround

**Comment by misha-pavlov** [comment]
Any updates here?
