### ISSUE TITLE
RNEncryptedStorageModule.java line 77, Causing crashes on Android

### ISSUE THREAD

**Issue by firstfloordigital** [emeraldsanto/react-native-encrypted-storage#31]
RNEncryptedStorageModule.java line 77
com.emeraldsanto.encryptedstorage.RNEncryptedStorageModule.getItem

![image](https://user-images.githubusercontent.com/52122775/98201288-5a253080-1f55-11eb-941f-3c9639feab02.png)

**Comment by emeraldsanto** [comment]
This [issue](https://github.com/google/tink/issues/321) could be helpful.

The linked issue says it seems to happen only on certain devices; can you tell me on which device you're experiencing this crash?

**Comment by firstfloordigital** [comment]
I don't think this issue is a device-specific one.
Here is the list of devices that have faced crashes though
Samsung Galaxy Note8
Xiaomi Mi A3
Nokia 7.2
ONEPLUS 6
all the crash reported are on android 9 and android 10.

**Comment by shridhar52war** [comment]
We are also facing a lot of crashes on production, mostly with Android 5.X.X. 
Any quick fix for this?

<img width="1132" alt="Screenshot 2020-12-07 at 10 19 09 AM" src="https://user-images.githubusercontent.com/56016210/101310994-63682c80-3876-11eb-86e3-db5a1d62f73e.png">

**Comment by emeraldsanto** [comment]
I have just released version 4.0.1 which moves away from some deprecations on the Android side as well as updates the security package dependency. Do you mind giving it a try?
