### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by shridhar52war** [emeraldsanto/react-native-encrypted-storage#33]
Facing a lot of crashes on Android in production.
<img width="442" alt="Screenshot 2020-12-07 at 10 47 26 AM" src="https://user-images.githubusercontent.com/56016210/101312508-eb9c0100-3879-11eb-8bf8-8a68b23aa73b.png">

<img width="1132" alt="Screenshot 2020-12-07 at 10 19 09 AM" src="https://user-images.githubusercontent.com/56016210/101312493-e343c600-3879-11eb-9c39-ba098d2812d5.png">

Most of the crashes are happening on Android 5.x.x. 
Any solutions?

**Comment by shubhnik** [comment]
Facing the same issue on Android 5.x.x devices. Does this library have any minimum Android API requirements?

**Comment by emeraldsanto** [comment]
Yes, due to limitations of the `androidx.security:security-crypto` dependency, the `minSdkVersion` is currently set to `23` while Android 5 is `21`. I have just finalized testing of #35 which will bring support to `<= 21`.

**Comment by emeraldsanto** [comment]
This has been published on npm under the `4.0.0` version: https://github.com/emeraldsanto/react-native-encrypted-storage/releases/tag/4.0.0
