### ISSUE TITLE
React Native Encrypted Storage Error: RNEncryptedStorage is undefined

### ISSUE THREAD

**Issue by 0526tracy** [emeraldsanto/react-native-encrypted-storage#34]
Hi !is anyone here ever encountered this?

Im using expo in my current project, then i tried to use react-native-encrypted-storage
I follow the steps  here (https://www.npmjs.com/package/react-native-encrypted-storage)

but i got this error when i run expo start

![image](https://user-images.githubusercontent.com/37529355/102456631-6fc16600-407c-11eb-863f-a6e9fdc7701a.png)

**Comment by emeraldsanto** [comment]
This module does not support Expo since it uses native code.

**Comment by phuvinhng** [comment]
I don't use expo but I still get that error !! @emeraldsanto

**Comment by TrebuhD** [comment]
@phuvinhng inside your `__mocks__` directory, create a file called `react-native.js` with the following content:

```javascript
module.exports = {
  NativeModules: {
    RNEncryptedStorage: {
      store: jest.fn(() => Promise.resolve()),
      retrieve: jest.fn(() => Promise.resolve('{ "foo": 1 }')),
      remove: jest.fn(() => Promise.resolve()),
    },
  },
};
```

[source](https://github.com/emeraldsanto/react-native-encrypted-storage/pull/1/files)

**Comment by CaLxCyMru** [comment]
If someone happens to stumble across this issue try the following steps:

1. Run `cd ios && pod install && cd ..`
2. Stop all `metro` servers
3. Re-build the `iOS` app with `yarn run ios`

Final step seems to have resolved the issue for me 👌
