### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by bilginmusa** [emeraldsanto/react-native-encrypted-storage#38]
Hi,

It's working on android, but I tested on iOS it's not working. You can find error description below.

[!] CocoaPods could not find compatible versions for pod "react-native-encrypted-storage":
  In Podfile:
    react-native-encrypted-storage (from `../node_modules/react-native-encrypted-storage`)

Specs satisfying the `react-native-encrypted-storage (from `../node_modules/react-native-encrypted-storage`)` dependency were found, but they required a higher minimum deployment target. 

react-native-cli: 2.0.1
react-native: 0.61.5

**Comment by emeraldsanto** [comment]
The library is set to target iOS 10.0, which is what the error says

> Specs satisfying the react-native-encrypted-storage (from ../node_modules/react-native-encrypted-storage) dependency were found, but they required a higher minimum deployment target.

Which iOS version is your app built for?
