### ISSUE TITLE
App starting is slow when using EncryptedStorage with redux on Android

### ISSUE THREAD

**Issue by OmarBasem** [emeraldsanto/react-native-encrypted-storage#39]
I was looking for a redux encrypted storage. I tried several other libraries, but none of them worked properly on Android till I came across this one. In this library, every thing is working properly, but the time between after the splash screen is done and the home screen rendering is a little bit slow, takes about 3 seconds, and sometimes randomly takes up to 6 seconds. Is there any configurations that can be done to make the decryption process faster, or maybe some part of the native code on Android needs to be optimized?

**Comment by emeraldsanto** [comment]
Are you performing multiple `RNEncryptedStorage.getIem()` at startup? This could explain the delay since the library doesn't yet expose a `multiGet()` so all calls are made individually.
