### ISSUE TITLE
How can I ensure that stored data is encrypted in device storage?

### ISSUE THREAD

**Issue by sivaperumaljeyaraj** [emeraldsanto/react-native-encrypted-storage#43]
Hi, I have used this plugin in my project for secure storage of sensitive data in devices. As Encryption and Decryption mechanism happens implicitly in the plugin, how can I ensure that stored data is encrypted in device storage?

Please clarify it.

**Comment by emeraldsanto** [comment]
This library uses the the Keychain API on iOS and EncryptedSharedPreferences on Android. You can read more about their encryption mechanisms:

- https://support.apple.com/en-ca/guide/security/secb0694df1a/web
- https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences
