### ISSUE TITLE
RNEncryptedStorageError: An error occured while retrieving value

### ISSUE THREAD

**Issue by jonathanroze** [emeraldsanto/react-native-encrypted-storage#58]
Hi, 

I've this error multiple times across multiple users on IOS

`RNEncryptedStorageError: An error occured while retrieving value`

![Capture d’écran 2021-08-11 à 07 05 29](https://user-images.githubusercontent.com/2753799/128972750-ab238d9d-362d-4a38-8f1e-712a19304f2f.png)

Thanks

**Comment by emeraldsanto** [comment]
Hello! This can happen for many different reasons, you can find the specific iOS security framework error code by checking the `e.code` property as mentioned in the [docs](https://github.com/emeraldsanto/react-native-encrypted-storage#error-handling) (only on iOS). You can then look up the meaning of the error code [here](https://www.osstatus.com/).
