### ISSUE TITLE
jcenter to mavenCentral

### ISSUE THREAD

**Issue by mazemapdeveloper** [emeraldsanto/react-native-encrypted-storage#71]
hi,

as jcenter will shutdown by feb 2022, it needs to be replaced with mavenCentral in gradle build file. May I know when will that be done?

Thanks

**Comment by douglasjunior** [comment]
Up

**Comment by emeraldsanto** [comment]
Very good point, this is coming in version 5, you can use the `v5` branch until I publish it officially.
